### ISSUE TITLE
Getting window is not defined

### ISSUE THREAD

**Issue by coguy450** [georgeOsdDev/react-notification-badge#17]
I'm getting an error when I import the example into my code. window is not defined at node_modules/react-notification-badge/lib/components/AnimationCounter.js 33.2

When I tried to do an npm-install, I got redux-async-connect@1.0.0-rc4 requires a peer of react@0.14.x but none was installed.

We are on React 15.4. Is this package just not compatible with React 15.x?

**Comment by georgeOsdDev** [comment]
This package depend on React ^15.0.1
https://github.com/georgeOsdDev/react-notification-badge/blob/master/package.json#L62
Please tell me your app's `package.json`.

By the way,I'm not sure `window is not defined` is caused by React version issue.
It seems to be issue related with build flow like browserify or webpack.

**Comment by coguy450** [comment]
Yes, it could be a webpack issue, if no other users have had this problem, we can close this issue.
